// <auto-generated />
using System;
using FondsSocial.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FondsSocial.Infrastructure.Migrations
{
    [DbContext(typeof(FondsSocialDbContext))]
    [Migration("20260715025648_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FondsSocial.Domain.Entities.Agent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adresse")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("CIN")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateTitularisation")
                        .HasColumnType("datetime2");

                    b.Property<string>("Fonction")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Grade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdentifiantUnique")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Matricule")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("NombreEnfantsACharge")
                        .HasColumnType("int");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("SituationFamiliale")
                        .HasColumnType("int");

                    b.Property<int>("SocieteId")
                        .HasColumnType("int");

                    b.Property<string>("Telephone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CIN")
                        .IsUnique()
                        .HasDatabaseName("IX_Agent_CIN");

                    b.HasIndex("IdentifiantUnique")
                        .IsUnique()
                        .HasDatabaseName("IX_Agent_IdentifiantUnique");

                    b.HasIndex("Matricule")
                        .IsUnique()
                        .HasDatabaseName("IX_Agent_Matricule");

                    b.HasIndex("SocieteId");

                    b.ToTable("Agents", (string)null);
                });

            modelBuilder.Entity("FondsSocial.Domain.Entities.BudgetFonds", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Categorie")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Emplois")
                        .HasColumnType("decimal(18,3)");

                    b.Property<int>("Exercice")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal>("Ressources")
                        .HasColumnType("decimal(18,3)");

                    b.Property<int>("SocieteId")
                        .HasColumnType("int");

                    b.Property<decimal>("Solde")
                        .HasColumnType("decimal(18,3)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SocieteId", "Exercice", "Categorie")
                        .IsUnique()
                        .HasDatabaseName("IX_BudgetFonds_Societe_Exercice_Categorie");

                    b.ToTable("BudgetFonds", (string)null);
                });

            modelBuilder.Entity("FondsSocial.Domain.Entities.Contrat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DatePremiereEcheance")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateSignature")
                        .HasColumnType("datetime2");

                    b.Property<int>("DecisionId")
                        .HasColumnType("int");

                    b.Property<int>("DureeMois")
                        .HasColumnType("int");

                    b.Property<decimal>("FraisGestion")
                        .HasColumnType("decimal(18,3)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal>("MontantPrincipal")
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal>("MontantTotal")
                        .HasColumnType("decimal(18,3)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DecisionId")
                        .IsUnique();

                    b.ToTable("Contrats", (string)null);
                });

            modelBuilder.Entity("FondsSocial.Domain.Entities.Decision", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateNotification")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DatePeremption")
                        .HasColumnType("datetime2");

                    b.Property<int>("DemandeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal?>("MontantAccorde")
                        .HasColumnType("decimal(18,3)");

                    b.Property<int>("SeanceComiteId")
                        .HasColumnType("int");

                    b.Property<int>("SensDecision")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DemandeId");

                    b.HasIndex("SeanceComiteId");

                    b.ToTable("Decisions", (string)null);
                });

            modelBuilder.Entity("FondsSocial.Domain.Entities.Demande", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AgentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateDepot")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal>("MontantDemande")
                        .HasColumnType("decimal(18,3)");

                    b.Property<string>("NumeroDossier")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("ScorePriorite")
                        .HasColumnType("decimal(18,3)");

                    b.Property<int>("StatutCourant")
                        .HasColumnType("int");

                    b.Property<int>("TypeDePretId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.HasIndex("NumeroDossier")
                        .IsUnique()
                        .HasDatabaseName("IX_Demande_NumeroDossier");

                    b.HasIndex("TypeDePretId");

                    b.ToTable("Demandes", (string)null);
                });

            modelBuilder.Entity("FondsSocial.Domain.Entities.Echeance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CapitalAmorti")
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal>("CapitalRestantDu")
                        .HasColumnType("decimal(18,3)");

                    b.Property<int>("ContratId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("FraisGestion")
                        .HasColumnType("decimal(18,3)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal>("Mensualite")
                        .HasColumnType("decimal(18,3)");

                    b.Property<int>("NumeroEcheance")
                        .HasColumnType("int");

                    b.Property<decimal>("SoldeRestant")
                        .HasColumnType("decimal(18,3)");

                    b.Property<int>("Statut")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ContratId", "NumeroEcheance")
                        .IsUnique()
                        .HasDatabaseName("IX_Echeance_Contrat_Numero");

                    b.ToTable("Echeances", (string)null);
                });

            modelBuilder.Entity("FondsSocial.Domain.Entities.Garantie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AssuranceVieSouscrite")
                        .HasColumnType("bit");

                    b.Property<bool>("AutorisationRetenueSalaireSignee")
                        .HasColumnType("bit");

                    b.Property<int>("ContratId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateAssuranceVie")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateAutorisationRetenue")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateEngagement")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateTraite")
                        .HasColumnType("datetime2");

                    b.Property<bool>("EngagementRemboursementSigne")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ReferencePoliceAssurance")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("TraiteSigneeLegalisee")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ContratId")
                        .IsUnique();

                    b.ToTable("Garanties", (string)null);
                });

            modelBuilder.Entity("FondsSocial.Domain.Entities.HistoriqueStatutDemande", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Auteur")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Commentaire")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateChangement")
                        .HasColumnType("datetime2");

                    b.Property<int>("DemandeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Statut")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DemandeId");

                    b.ToTable("HistoriqueStatutDemandes", (string)null);
                });

            modelBuilder.Entity("FondsSocial.Domain.Entities.MembreComite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Actif")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fonction")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MembreComites", (string)null);
                });

            modelBuilder.Entity("FondsSocial.Domain.Entities.ParticipationSeance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AVise")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateVisa")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("MembreComiteId")
                        .HasColumnType("int");

                    b.Property<int>("SeanceComiteId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MembreComiteId");

                    b.HasIndex("SeanceComiteId", "MembreComiteId")
                        .IsUnique()
                        .HasDatabaseName("IX_ParticipationSeance_Seance_Membre");

                    b.ToTable("ParticipationSeances", (string)null);
                });

            modelBuilder.Entity("FondsSocial.Domain.Entities.PieceJustificative", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CheminFichier")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateDepot")
                        .HasColumnType("datetime2");

                    b.Property<int>("DemandeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("StatutVerification")
                        .HasColumnType("int");

                    b.Property<string>("TypePiece")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DemandeId");

                    b.ToTable("PieceJustificatives", (string)null);
                });

            modelBuilder.Entity("FondsSocial.Domain.Entities.PieceJustificativeRequise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LibellePiece")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("Obligatoire")
                        .HasColumnType("bit");

                    b.Property<int>("TypeDePretId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TypeDePretId");

                    b.ToTable("PieceJustificativeRequises", (string)null);
                });

            modelBuilder.Entity("FondsSocial.Domain.Entities.RetenueMensuelle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AgentId")
                        .HasColumnType("int");

                    b.Property<int>("ContratId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Mois")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("MontantARetenir")
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal?>("MontantEffectivementRetenu")
                        .HasColumnType("decimal(18,3)");

                    b.Property<string>("ReferencePaie")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Statut")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.HasIndex("ContratId", "Mois")
                        .IsUnique()
                        .HasDatabaseName("IX_Retenue_Contrat_Mois");

                    b.ToTable("RetenuesMensuelles", (string)null);
                });

            modelBuilder.Entity("FondsSocial.Domain.Entities.SeanceComite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ProcesVerbal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StatutVisaSignature")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SeanceComites", (string)null);
                });

            modelBuilder.Entity("FondsSocial.Domain.Entities.Societe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("RaisonSociale")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("ReferentielReglesGestion")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("IX_Societe_Code");

                    b.ToTable("Societes", (string)null);
                });

            modelBuilder.Entity("FondsSocial.Domain.Entities.TypeDePret", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Actif")
                        .HasColumnType("bit");

                    b.Property<int>("Categorie")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DureeMaxMois")
                        .HasColumnType("int");

                    b.Property<int>("FranchiseMois")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ModeCalculFraisGestion")
                        .HasColumnType("int");

                    b.Property<decimal>("Plafond")
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal>("TauxOuMontantFraisGestion")
                        .HasColumnType("decimal(18,3)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("IX_TypeDePret_Code");

                    b.ToTable("TypeDePrets", (string)null);
                });

            modelBuilder.Entity("FondsSocial.Domain.Entities.Agent", b =>
                {
                    b.HasOne("FondsSocial.Domain.Entities.Societe", "Societe")
                        .WithMany("Agents")
                        .HasForeignKey("SocieteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Societe");
                });

            modelBuilder.Entity("FondsSocial.Domain.Entities.BudgetFonds", b =>
                {
                    b.HasOne("FondsSocial.Domain.Entities.Societe", "Societe")
                        .WithMany("BudgetFonds")
                        .HasForeignKey("SocieteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Societe");
                });

            modelBuilder.Entity("FondsSocial.Domain.Entities.Contrat", b =>
                {
                    b.HasOne("FondsSocial.Domain.Entities.Decision", "Decision")
                        .WithOne("Contrat")
                        .HasForeignKey("FondsSocial.Domain.Entities.Contrat", "DecisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Decision");
                });

            modelBuilder.Entity("FondsSocial.Domain.Entities.Decision", b =>
                {
                    b.HasOne("FondsSocial.Domain.Entities.Demande", "Demande")
                        .WithMany("Decisions")
                        .HasForeignKey("DemandeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FondsSocial.Domain.Entities.SeanceComite", "SeanceComite")
                        .WithMany("Decisions")
                        .HasForeignKey("SeanceComiteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Demande");

                    b.Navigation("SeanceComite");
                });

            modelBuilder.Entity("FondsSocial.Domain.Entities.Demande", b =>
                {
                    b.HasOne("FondsSocial.Domain.Entities.Agent", "Agent")
                        .WithMany("Demandes")
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FondsSocial.Domain.Entities.TypeDePret", "TypeDePret")
                        .WithMany("Demandes")
                        .HasForeignKey("TypeDePretId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Agent");

                    b.Navigation("TypeDePret");
                });

            modelBuilder.Entity("FondsSocial.Domain.Entities.Echeance", b =>
                {
                    b.HasOne("FondsSocial.Domain.Entities.Contrat", "Contrat")
                        .WithMany("Echeances")
                        .HasForeignKey("ContratId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contrat");
                });

            modelBuilder.Entity("FondsSocial.Domain.Entities.Garantie", b =>
                {
                    b.HasOne("FondsSocial.Domain.Entities.Contrat", "Contrat")
                        .WithOne("Garantie")
                        .HasForeignKey("FondsSocial.Domain.Entities.Garantie", "ContratId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contrat");
                });

            modelBuilder.Entity("FondsSocial.Domain.Entities.HistoriqueStatutDemande", b =>
                {
                    b.HasOne("FondsSocial.Domain.Entities.Demande", "Demande")
                        .WithMany("HistoriqueStatuts")
                        .HasForeignKey("DemandeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Demande");
                });

            modelBuilder.Entity("FondsSocial.Domain.Entities.ParticipationSeance", b =>
                {
                    b.HasOne("FondsSocial.Domain.Entities.MembreComite", "MembreComite")
                        .WithMany("Participations")
                        .HasForeignKey("MembreComiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FondsSocial.Domain.Entities.SeanceComite", "SeanceComite")
                        .WithMany("Participations")
                        .HasForeignKey("SeanceComiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MembreComite");

                    b.Navigation("SeanceComite");
                });

            modelBuilder.Entity("FondsSocial.Domain.Entities.PieceJustificative", b =>
                {
                    b.HasOne("FondsSocial.Domain.Entities.Demande", "Demande")
                        .WithMany("PieceJustificatives")
                        .HasForeignKey("DemandeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Demande");
                });

            modelBuilder.Entity("FondsSocial.Domain.Entities.PieceJustificativeRequise", b =>
                {
                    b.HasOne("FondsSocial.Domain.Entities.TypeDePret", "TypeDePret")
                        .WithMany("PiecesJustificativesRequises")
                        .HasForeignKey("TypeDePretId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TypeDePret");
                });

            modelBuilder.Entity("FondsSocial.Domain.Entities.RetenueMensuelle", b =>
                {
                    b.HasOne("FondsSocial.Domain.Entities.Agent", "Agent")
                        .WithMany("RetenuesMensuelles")
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FondsSocial.Domain.Entities.Contrat", "Contrat")
                        .WithMany("RetenuesMensuelles")
                        .HasForeignKey("ContratId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Agent");

                    b.Navigation("Contrat");
                });

            modelBuilder.Entity("FondsSocial.Domain.Entities.Agent", b =>
                {
                    b.Navigation("Demandes");

                    b.Navigation("RetenuesMensuelles");
                });

            modelBuilder.Entity("FondsSocial.Domain.Entities.Contrat", b =>
                {
                    b.Navigation("Echeances");

                    b.Navigation("Garantie");

                    b.Navigation("RetenuesMensuelles");
                });

            modelBuilder.Entity("FondsSocial.Domain.Entities.Decision", b =>
                {
                    b.Navigation("Contrat");
                });

            modelBuilder.Entity("FondsSocial.Domain.Entities.Demande", b =>
                {
                    b.Navigation("Decisions");

                    b.Navigation("HistoriqueStatuts");

                    b.Navigation("PieceJustificatives");
                });

            modelBuilder.Entity("FondsSocial.Domain.Entities.MembreComite", b =>
                {
                    b.Navigation("Participations");
                });

            modelBuilder.Entity("FondsSocial.Domain.Entities.SeanceComite", b =>
                {
                    b.Navigation("Decisions");

                    b.Navigation("Participations");
                });

            modelBuilder.Entity("FondsSocial.Domain.Entities.Societe", b =>
                {
                    b.Navigation("Agents");

                    b.Navigation("BudgetFonds");
                });

            modelBuilder.Entity("FondsSocial.Domain.Entities.TypeDePret", b =>
                {
                    b.Navigation("Demandes");

                    b.Navigation("PiecesJustificativesRequises");
                });
#pragma warning restore 612, 618
        }
    }
}
